FROM node:18-alpine

WORKDIR /app

# Copy backend
COPY backend ./backend
RUN cd backend && npm install express

# Copy load balancer
COPY loadBalancer ./loadBalancer
RUN cd loadBalancer && npm install express

EXPOSE 8080

# Start 3 backend replicas + load balancer
CMD node backend/server.js & \
    node backend/server.js & \
    node backend/server.js & \
    node loadBalancer/loadBalancer.js
